<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2015.0.2.310
*/

require_once('form_process.php');

$form = array(
	'subject' => 'DIRECT DEPOSIT Form Submission',
	'heading' => 'New Form Submission',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Checked',
		'checkbox_unchecked' => 'Unchecked',
		'submitted_from' => 'Form submitted from website: %s',
		'submitted_by' => 'Visitor IP address: %s',
		'too_many_submissions' => 'Too many recent submissions from this IP',
		'failed_to_send_email' => 'Failed to send email',
		'invalid_reCAPTCHA_private_key' => 'Invalid reCAPTCHA private key.',
		'invalid_field_type' => 'Unknown field type \'%s\'.',
		'invalid_form_config' => 'Field \'%s\' has an invalid configuration.',
		'unknown_method' => 'Unknown server request method'
	),
	'email' => array(
		'from' => 'davidk@transcash.com',
		'to' => 'davidk@transcash.com'
	),
	'fields' => array(
		'custom_U719' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Account Type',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Account Type\' is required.'
			)
		),
		'Email' => array(
			'order' => 2,
			'type' => 'email',
			'label' => 'Deposit Type',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Deposit Type\' is required.',
				'format' => 'Field \'Deposit Type\' has an invalid email.'
			)
		),
		'custom_U712' => array(
			'order' => 6,
			'type' => 'string',
			'label' => 'Deposit Order Notes',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U761' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Amount: $',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Amount: $\' is required.'
			)
		),
		'custom_U765' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Routing #',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Routing #\' is required.'
			)
		),
		'custom_U769' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'Account #',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Account #\' is required.'
			)
		)
	)
);

process_form($form);
?>
